name: UpdateAlerts
on:
  schedule:
    - cron: '*/5 * * * *' # Проверка каждые 5 минут
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run scraper
        run: python scraper.py
      - name: Commit and Push
        run: |
          git config --global user.name "AlertBot"
          git config --global user.email "bot@alert.com"
          git add data.json
          git commit -m "Auto-update" || exit 0
          git push
